### ISSUE TITLE
Create a Glossary page

### ISSUE THREAD

**Issue by jendiamond** [Jorellana90/progressportal#27]
+ decide whether you need a page to explain each glossary entry further
+ link to page if one exists
+ alphabetize  the glossary
----
first term:
### semantic versioning
[Wikipedia](https://en.wikipedia.org/wiki/Software_versioning) The process release of assigning either unique version names or unique version numbers to unique states of computer software. Within a given version number category (major, minor), these numbers are generally assigned in increasing order and correspond to new developments in the software. At a fine-grained level, revision control is often used for keeping track of incrementally different versions of information, whether or not this information is computer software.  
**v1.0.0**
+ MAJOR 
    + version when you make incompatible API changes
     + Increment the first digit by 1 if the new features break backwards compatibility/current features
+ MINOR 
    + version when you add functionality in a backwards-compatible manner
    +  Increment the middle digit by 1 if the new features don’t break any existing features and are compatible with the app in it’s current state
+ PATCH 
    + version when you make backwards-compatible bug fixes
    +  Increment the last digit by 1 if you’re publishing bug/patch fixes to your app
#### READ
https://medium.com/@jameshamann/a-brief-guide-to-semantic-versioning-c6055d87c90e

### Add more terms

**Comment by Jorellana90** [comment]
All done! The glossary page now has its first term, definition and link to the additional reading!
